### ISSUE TITLE
Contar emails

### ISSUE THREAD

**Issue by manujp262** [manujp262/CrushMail#1]
Como SISTEMA quiero contar el número de emails que existen en mi bandeja de entrada por remitente de modo que pueda generar una estadística de los remitentes más habituales

**Comment by profeIAP** [comment]
Te será de utilidad este fragmento de código

```
// NOTA el guión bajo tras el nombre es para evitar que aparezca como función de macro

const log_=(...data)=>{
  data.unshift(new Date()); 
  SpreadsheetApp.getActive().getSheetByName("log").appendRow(data);
}

function procesarIncidencias() {

  sinLeer=GmailApp.getInboxUnreadCount();
  log_(`${sinLeer} correos sin leer`);
  
  // Se puede limitar el numero de hilos a procesar con .getInboxThreads(n,m)
  // emails = GmailApp.getUserLabelByName(ETQ_ANOTACION).getThreads();

  emails=GmailApp.getInboxThreads();
  
  emails.forEach(procesarEmail_);
 
}

function procesarEmail_(hilo){

  var id=hilo.getId();
  var asunto=hilo.getFirstMessageSubject();

  log_(`Procesamos [${id}] - "${asunto}"`);
}

```

**Comment by manujp262** [comment]
const log_=(...data)=>{
  data.unshift(new Date()); 
  SpreadsheetApp.getActive().getSheetByName("log").appendRow(data);
}


function procesarIncidencias() { 
  emails=GmailApp.getInboxThreads(); 
  emails.forEach(remitenteEmail_);
}

function remitenteEmail_(hilo) {
//var thread = GmailApp.getInboxThreads(); // Get first thread in inbox
var message = hilo.getMessages()[0]; // Get first message
log_(message.getFrom()); // Log from address of the message
}

**Comment by manujp262** [comment]
> const log_=(...data)=>{
  data.unshift(new Date()); 
  SpreadsheetApp.getActive().getSheetByName("log").appendRow(data);
}


function procesarIncidencias() { 
  emails=GmailApp.getInboxThreads(); 
  emails.forEach(remitenteEmail_);
}

function remitenteEmail_(hilo) {
//var thread = GmailApp.getInboxThreads(); // Get first thread in inbox
var message = hilo.getMessages()[0]; // Get first message
log_(message.getFrom()); // Log from address of the message
}

**Comment by manujp262** [comment]
Resultado 
`const log_=(...data)=>{
  data.unshift(new Date()); 
  SpreadsheetApp.getActive().getSheetByName("log").appendRow(data);
}


function procesarIncidencias() { 
  emails=GmailApp.getInboxThreads(); 
  emails.forEach(remitenteEmail_);
}

function remitenteEmail_(hilo) {
//var thread = GmailApp.getInboxThreads(); // Get first thread in inbox
var message = hilo.getMessages()[0]; // Get first message
log_(message.getFrom()); // Log from address of the message
}
`

**Comment by profeIAP** [comment]
@manujp262 ya que no tenemos el código (existe formas pero no nos vamos a meter en "jaleos" ¿verdad?) opta por enlazar [en el fichero README.md](https://github.com/manujp262/CrushMail/blob/main/README.md) la hoja de cálculo que estás utilizando para que pueda mirar directamente cómo lo llevas

Aquí, te quedaría más sencillo (y mejor) hacer una captura de código y pegar la imagen en tus comentarios (el anterior bloque de código ha quedado algo "feote") 👍🏻 

Buen trabajo, hoy has avanzado bastante

**Comment by manujp262** [comment]
Ya he enlazado la hoja de calculo al fichero README.md

**Comment by manujp262** [comment]
Me podría echar una mano con este código. Mi intención es que cree automáticamente etiquetas con el nombre del remitente.
Parece que funciona bien pero tengo un mal presentimiento por lo que todavía no lo he añadido al proyecto.

> 
function procesarIncidencias() { 
  emails=GmailApp.getInboxThreads(); 
  emails.forEach(etiquetado_);
}

function etiquetado_(hilo) { 
  var message = hilo.getMessages()[0]; // Get first message
  emisor=message.getFrom()
  GmailApp.createLabel(emisor)
  hilo.addLabel(GmailApp.getUserLabelByName(emisor));
}

**Comment by profeIAP** [comment]
Etiquetas incorrectas

**Comment by profeIAP** [comment]
NO Abro la tarea por no tener proyecto asignado al haberlo comentado en #13
