### ISSUE TITLE
Organizar correctamente las tareas

### ISSUE THREAD

**Issue by profeIAP** [manujp262/CrushMail#13]
En la tarea #8 ya hablamos de la necesidad de etiquetar correctamente las tareas.
En las últimas observo que estás descuidando igualmente sprint e historia de usuario

![imagen](https://user-images.githubusercontent.com/16881846/118229856-04de5480-b48d-11eb-92ab-c6fb4c8b321a.png)

**Comment by profeIAP** [comment]
Etiquetas incorrecatas

**Comment by profeIAP** [comment]
Quedan detalles como:
1. Tareas sin milestone 
![imagen](https://user-images.githubusercontent.com/16881846/119551501-00be0b00-bd9a-11eb-9240-7014a5933fc7.png)
1. O sin proyecto asignado 
![imagen](https://user-images.githubusercontent.com/16881846/119551560-0fa4bd80-bd9a-11eb-81c2-af333a7b596c.png)

De las etiquetas ya hemos hablado en #8

**Comment by profeIAP** [comment]
Pues sigo sin estar de acuerdo

![imagen](https://user-images.githubusercontent.com/16881846/119942846-915f3b80-bf92-11eb-844d-57c532178d82.png)

**Comment by manujp262** [comment]
Solucionado

**Comment by profeIAP** [comment]
Ahora sí, perfect 😏 👍🏻
