### ISSUE TITLE
Crear una función que identifique si contiene algun archivo en su interior

### ISSUE THREAD

**Issue by manujp262** [manujp262/CrushMail#15]

**Comment by profeIAP** [comment]
Realmente no compruebas que se trate de un pdf sino que tenga algún adjunto con "contenido"

![imagen](https://user-images.githubusercontent.com/16881846/119942056-aedfd580-bf91-11eb-8549-c8d785f44471.png)

**Comment by manujp262** [comment]
Funciona para todo tipo de archivos : fotos, documentos de texto, pdf, video...
Es verdad que podría haber especificado más el tipo de archivo
