### ISSUE TITLE
Crear una función que etiquete los emails con contenido para evitar que sean borrados

### ISSUE THREAD

**Issue by manujp262** [manujp262/CrushMail#16]

**Comment by profeIAP** [comment]
Interesante: ¿no da problemas si la etiqueta ya existe?

![imagen](https://user-images.githubusercontent.com/16881846/119943238-0b8fc000-bf93-11eb-9f9a-4eeda4d8e4be.png)

**Comment by manujp262** [comment]
No da ningún tipo de error.
Las etiquetas funcionan de forma curiosa y si se crea una etiqueta con el mismo nombre se "fusionan" dando lugar a una sola etiqueta.
En la función de etiquetado se ve claramente, crea una nueva etiqueta con el nombre del remitente de cada correo y como el remitente se repite quedan almacenadas en una sola.

**Comment by profeIAP** [comment]
Hemos visto que es así 👍🏻
