### ISSUE TITLE
Extraer de cada email el remitente

### ISSUE THREAD

**Issue by manujp262** [manujp262/CrushMail#5]

**Comment by profeIAP** [comment]
Perfect

**Comment by profeIAP** [comment]
Pensaba que estaba perfecta hasta que he visto las etiquetas usadas (no cumplen el estándar)

**Comment by profeIAP** [comment]
Perfecto 
![imagen](https://user-images.githubusercontent.com/16881846/119551949-788c3580-bd9a-11eb-889d-f955629617bd.png)
