### ISSUE TITLE
Procesar las etiquetas para sacar la cantidad de etiquetas por email

### ISSUE THREAD

**Issue by manujp262** [manujp262/CrushMail#9]

**Comment by profeIAP** [comment]
El atributo `length` hace milagros
Aquí un artículo explicando [cómo hacer una búsqueda por etiqueta](https://javascript.plainenglish.io/apps-script-example-project-get-the-number-of-emails-with-a-specific-label-d7e1fb2e998b) y periodo (esto último no lo necesitas)

**Comment by profeIAP** [comment]
Etiquetas incorrectas

**Comment by profeIAP** [comment]
Estupendo 
![imagen](https://user-images.githubusercontent.com/16881846/119552155-b2f5d280-bd9a-11eb-9eac-2f362efeabcf.png)
